### ISSUE TITLE
What does MntGoldProds mean?

### ISSUE THREAD

**Issue by lyt-lucy** [nailson/ifood-data-business-analyst-test#1]
Why does vendors of food have data about spending on gold?

**Comment by nailson** [comment]
Oh, this is basically a boolean column saying if it is a regular or gold category of products.
The description in the dictionary is pretty odd about this but [this](https://github.com/nailson/ifood-data-business-analyst-test/blob/master/iFood%20Data%20Analyst%20Case.pdf) explanation in the second page explains it
